[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build-meta"

[project]
name = "poker_engine"
version = "0.1.0"
description = "A logic engine for poker games"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]